#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          xivo-recording
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      xivo-recording
# Should-Stop:       xivo-recording
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup daemon script for xivo-recording
### END INIT INFO
#
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMONNAME=xivo_recording
DAEMON=/usr/local/bin/$DAEMONNAME
DAEMON_ARGS=$2
PIDFILE=/var/run/$DAEMONNAME.pid

. /lib/lsb/init-functions

test -x $DAEMON || exit 0


case "$1" in
  start)
    log_daemon_msg "Starting" "$DAEMONNAME"
    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping" "$DAEMONNAME"
    if start-stop-daemon --stop --quiet --oknodo --retry 5 --pidfile $PIDFILE;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    rm -f $PIDFILE
    ;;
  reload|force-reload)
    log_daemon_msg "Reloading" "$DAEMONNAME"
    if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE "$DAEMON" $DAEMONNAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|reload|force-reload|restart|status}"
    exit 1
    ;;
esac

exit 0
