services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - 9497

  provd:
    image: wazoplatform/wazo-provd
    ports:
      - "8666"
    volumes:
      - "./etc/wazo-provd/config.yml:/etc/wazo-provd/config.yml"
      - "./keys/wazo-provd-key.yml:/var/lib/wazo-auth-keys/wazo-provd-key.yml"
      - "./provd/null:/var/lib/wazo-provd/plugins/null"
      - "./provd/zero:/var/lib/wazo-provd/plugins/zero"
    command: "bash -c 'wazo-provd-upgrade-db && twistd --nodaemon --no_save --pidfile= wazo-provd --stderr --verbose'"

  postgres:
    image: wazoplatform/wazo-confd-db-test:local
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  sysconfd:
    image: wazoplatform/flask
    ports:
      - "8668"
    volumes:
      - "./mocks/sysconfd.py:/tmp/sysconfd.py"
    command: "python /tmp/sysconfd.py"

  confd:
    image: wazo-confd-test
    ports:
      - "9486"
    command: "wazo-confd -d"
    volumes:
      - "../..:/usr/src/wazo-confd"
      - "./etc/wazo-confd/conf.d/50-default.yml:/etc/wazo-confd/conf.d/50-default.yml"
      - "./doc/pjsip.json.gz:/usr/share/doc/asterisk-doc/json/pjsip.json.gz"
      # - "${LOCAL_GIT_REPOS}/wazo-auth-client/wazo_auth_client:/opt/venv/lib/python3.9/site-packages/wazo_auth_client"
      # - "${LOCAL_GIT_REPOS}/wazo-provd-client/wazo_provd_client:/opt/venv/lib/python3.9/site-packages/wazo_provd_client"
      # - "${LOCAL_GIT_REPOS}/wazo-bus/wazo_bus:/opt/venv/lib/python3.9/site-packages/wazo_bus"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/opt/venv/lib/python3.9/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.9/site-packages/xivo"
